# See for examples: https://github.com/htr3n/hyde-hyde/blob/master/exampleSite/config.toml

baseURL = "https://www.philipdaniels.com/"
languageCode = "en-us"
title = "Phil's Blog"
theme = "hyde-hyde-pd"
googleAnalytics = "UA-51573023-1"
disqusShortname = "philipdanielscomblog"
enableRobotsTXT = true

[params]
# This lot is for the hyde-hyde theme to make it use highlight.js instead of Hugo's
# built-in syntax highlighting (which is shit, wraps lines when it shouldn't).
# Get styles from https://highlightjs.org/static/demo/   Some nice ones:
# "darcula", "gruvbox-dark", "monokai","obsidian","pojoaque","rainbow","routeros",
# "railscasts","school-book","solarized-light","sunburst","tomorrow-night-bright"
# "tomorrow-night-eighties", "vs"
#
# https://highlightjs.readthedocs.io/en/latest/css-classes-reference.html#language-names-and-aliases
highlightjs = true
highlightjsstyle="gruvbox-dark"
highlightjslanguages = ["rust", "cs", "bash", "python", "css", "http", "ini", "javascript", "json",
"markdown", "sql", "html", "xml", "dockerfile", "scss", "r", "typescript", "go", "cpp", "dos",
"plaintext", "powershell", "diff", "makefile", "lisp"]
copyright = "Philip Daniels"
author = "Philip Daniels"
# showBuiltWith = true
dateformat = "Jan 2, 2006"

[params.social]
gravatar = "philip.daniels1971@gmail.com"
github = "PhilipDaniels"
stackoverflow = "1313057/philip-daniels"
email = "philip.daniels1971@gmail.com"

[[menu.main]]
    name = "Posts"
    identifier = "posts"
    weight = 100
    url = "/blog"
[[menu.main]]
    name = "My Git CheatSheet"
    identifier = "gitcheatsheet"
    weight = 200
    url = "/gitcheatsheet"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 400
    url = "/about"
